### ISSUE TITLE
cherry install has resolution to lower version

### ISSUE THREAD

**Issue by aleedmanath** [squint-cljs/compiler-common#8]
found cause of #7 

For whatever reason there is a resolution for `alpha.53`. I don't have that set in codebase, nor could I find it in cherry or compiler code, or search. I'm opening an issue in case it may be accidentally set and you know where/why. Otherwise feel free to close as I'm going to override it on my end.

```
"cherry-cljs@npm:^0.0.0-alpha.60":
  version: 0.0.0-mutable-alpha.53
  resolution: "cherry-cljs@npm:0.0.0-mutable-alpha.53"
  dependencies:
    argparse: ^2.0.1
    lodash: ^4.17.21
  bin:
    cherry: node_cli.js
  checksum: 4665045e4b22fadc8cdf6a45003cff3c1050f8c27795f05d2c65c077ef6014c6b447a51a32c48e28ec048a450c1436da77e8e2ce34221cdcb8bdeb9b6602dbe4
  languageName: node
  linkType: hard
```
